# -*- coding: utf-8 -*-
"""HelloWorld - LLM(Agentic FDP).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10GUxmdW-oikOBUGyXEAmynMC4Ti1f7RS
"""

!pip install google-genai

import os

# Replace with your actual key OR better yet, load it if already set!
os.environ["MY_GEMINI_API_KEY"] = "AIzaSyCznysnsApBt-_PzI-KS156EwwSCR6g2Z8"

import google.generativeai as genai
from google.genai import types
import os

# Ensure you have set the API key in the environment first!
genai.configure(api_key=os.environ["MY_GEMINI_API_KEY"])

from google.generativeai import types

# Select the model
model = genai.GenerativeModel('gemini-2.0-flash-lite')


# Define generation configuration
config = types.GenerationConfig(
    max_output_tokens=100,
    temperature=1.5  # informing the LLm as near to the learn data....if high temperature, then making it creative...eg for poem writing
)

# Generate content
response = model.generate_content(
    "write an essay about rains",
    generation_config=config
)
print(response.text)

# Define generation configuration
config = types.GenerationConfig(
    max_output_tokens=100,
    temperature=1.9  # informing the LLm as near to the learn data....if high temperature, then making it creative...eg for poem writing
)

# Generate content
response = model.generate_content(
    "write an essay about rains",
    generation_config=config
)
print(response.text)

# Define generation configuration
config = types.GenerationConfig(
    max_output_tokens=900,
    temperature=1.9  # informing the LLm as near to the learn data....if high temperature, then making it creative...eg for poem writing
)

# Generate content
response = model.generate_content(
    "Give me the receipe for a perfect chocolate cake",
    generation_config=config
)
print(response.text)